import Head from 'next/head'
import Image from 'next/image'
import { Sidebar, Feed, Login } from '../components'
import styles from '../styles/Home.module.css'
import {getProviders, getSession, useSession} from 'next-auth/react';


export default function Home(data) {
  console.log(data);
  // console.log(providers, trendingResults);
  // const {data: session} = useSession();
  // if(!session) return <Login  providers={providers} />
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col bg-black min-h-screen max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed />
        {/* Widgets */}

        {/* modals */}

      </main>
    </div>
  )
}


export async function getServerSidePorps(context) {
  const trendingResults = await fetch("https://jsonkeeper.com/b/NKEV").then(
    (res) => res.json()
  );
  const followResults = await fetch("https://jsonkeeper.com/b/WWMJ").then(
    (res) => res.json()
  );
   const providers = await getProviders();
  const session = await getSession(context);
  console.log("my providers =>",providers)
  return {
    props : {
      trendingResults,
      followResults,
      providers,
      session
    }
  }
}