import Head from 'next/head'
import Image from 'next/image'
import { Sidebar, Feed, Login, Widgets, CommentModal } from '../components'
import styles from '../styles/Home.module.css'
import {getProviders, getSession, useSession} from 'next-auth/react';
import { useRecoilState } from "recoil";
import { modalState } from '../atom/modal-atom';

export default function Home(data) {

  const {data: session} = useSession();
   const [isOpen, setIsOpen] = useRecoilState(modalState);

  const {trendingResults, followResults, providers} = data;
  console.log(data);
  if(!session) return <Login providers={providers}/>
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex  bg-black min-h-screen max-w-[1500px] mx-auto">
        <Sidebar />
        <Feed />
        <Widgets
          trendingResults={trendingResults}
          followResults={followResults}
        />

        {isOpen && <CommentModal />}

      </main>
    </div>
  )
}


export async function getServerSideProps(context) {
  
  const trendingResults = await fetch("https://jsonkeeper.com/b/NKEV").then(
    (res) => res.json()
  );
  const followResults = await fetch("https://jsonkeeper.com/b/WWMJ").then(
    (res) => res.json()
  );

  const providers = await getProviders();
  const session = await getSession(context);
  return {
    props : {
      trendingResults,
      followResults,
      providers,
      session
    }
  }
}